# Generated by Django 3.2.5 on 2021-07-27 15:13

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('news', '0003_blogpost_rutag_rutaggeditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='news.RuTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
