# Generated by Django 3.2.5 on 2021-07-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210727_2047'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='mytaggeditem',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='mytaggeditem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='mytaggeditem',
            name='tag',
        ),
        migrations.AlterUniqueTogether(
            name='mytagtranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mytagtranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='RuTag',
        ),
        migrations.DeleteModel(
            name='RuTaggedItem',
        ),
        migrations.DeleteModel(
            name='MyTag',
        ),
        migrations.DeleteModel(
            name='MyTaggedItem',
        ),
        migrations.DeleteModel(
            name='MyTagTranslation',
        ),
    ]
