# Generated by Django 3.2.5 on 2021-07-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210727_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=130, null=True, unique=True),
        ),
    ]
